[build]
target = "x86_64-unknown-none"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-none]
runner = "bootimage runner"
rustflags = [
    "-C", "relocation-model=static",
    "-C", "code-model=kernel",
    "-C", "no-redzone",
    "-C", "link-arg=-Tkernel/src/arch/x86_64/fabric_v10_gold.ld",
]
